version: '3.9'

services:
  db:
    restart: always
    image: postgres:14.7-alpine
    container_name: quiz_db
    env_file:
      - .env.docker
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d quiz_database" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend_quiz:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8006:8000'
    volumes:
      - .env.docker:/app/.env
    command: >
      bash -c "uvicorn app:app --host 0.0.0.0 --port 8000"

volumes:
  postgres_data: